services:
  # Frontend Next.js App
  - type: web
    name: livekit-warm-transfer-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_LIVEKIT_URL
        sync: false
      - key: NEXT_PUBLIC_LIVEKIT_API_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: https://livekit-warm-transfer-backend.onrender.com
    healthCheckPath: /
    
  # Backend Python API
  - type: web
    name: livekit-warm-transfer-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    healthCheckPath: /health